name: Build and Deploy to Cloud Run

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/devsecops-project-vuln/app-repo/vulnerable-web-app .
        docker push us-central1-docker.pkg.dev/devsecops-project-vuln/app-repo/vulnerable-web-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy vulnerable-web-app \
          --image=us-central1-docker.pkg.dev/devsecops-project-vuln/app-repo/vulnerable-web-app \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated 
# \
# --service-account="github-ci@devsecops-project-vuln.iam.gserviceaccount.com"